// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgents():Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function SendCommand(arg1:string,arg2:string,arg3:string):Promise<string>;
